name: test_mandatory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-mandatory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Bash Version
      run: bash --version
    - name: Make version
      run: make --version
    - name: Test Mandatory
      run: make test
